### PR TITLE
initial submission, Markup and JSX

### PR DESCRIPTION
**Pull request by derekschinke**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Derek!
Good job! Some corrections need to be made, but on the whole, the project is very impressive!

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
Couldn't find how to check the home page in a state when the user is logged in. Please, let me know how I can check the layout on home page, and the correct work of navigation between pages in logged in state, as the mockup suggests.
- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
* The links to external resources should open in new tabs.
* On saved-news page, the link to home page in the footer doesn't work.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [ ]  There are no validation errors.
https://prnt.sc/13hawq7
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.
`Registration successful` popup should be closed when the user clicks on `close` icon.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
* The bookmark on the news card (home page) should become blue on click (when logged in)
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
* "Search" form isn't highlighted
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [ ]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Raster and vector images have been optimized.

## Number of points: 53

**Comment by ImaliaNsk** [comment]
Thanks for the corrections! A few more fixes and the project will pass to the next stage!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
**The links to external resources should open in new tabs.**
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [ ]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
* "Search" form isn't highlighted
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Raster and vector images have been optimized.

## Number of points: 78

**Comment by derekschinke** [comment]
@ImaliaNsk what do you mean by ""Search" form isn't highlighted"? There's nothing in the Figma about that

**Comment by ImaliaNsk** [comment]
Perfect, the project has passed code review, thanks for the corrections and good luck on stage 3!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
**The links to external resources should open in new tabs.**
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
"Search" form input isn't highlighted. You're right, the figma mockup doesn't have this reflected, but this point in the checklist supposes that all elements inside forms which can be focused, are highlighted when they are. And the input inside the "search" form can be focused and highlighted as well
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Raster and vector images have been optimized.

## Number of points: 95

**Pull request merged**
